import CopyCommand from "./CopyCommand";

const TOOLS = [
  {
    name: "web_search",
    text: "Anthropic's hosted search tool, reserved for a genuine last resort when nothing else can answer the question. Capped at one search per turn. Real results, real URLs, cited at the end of the reply when it does fire.",
  },
  {
    name: "get_ecosystem_snapshot",
    text: "Re-pulls live snapshot or RPC heartbeat data on demand, for the freshest possible read.",
  },
  {
    name: "search_mantle_protocols",
    text: "Searches every protocol DefiLlama tracks on Mantle, not only the curated set, so the agent can answer about a protocol it wasn't pre-loaded with.",
  },
  {
    name: "get_protocol_detail",
    text: "Fetches live TVL detail for any single Mantle protocol by slug, with its DefiLlama source link.",
  },
];

const LAYERS = [
  {
    name: "Data",
    text: "Reads Mantle mainnet directly over its public RPC (viem) and pulls chain-wide and per-protocol historical TVL from DefiLlama's Mantle-specific slice, so a protocol's health is never diluted by activity on other chains.",
  },
  {
    name: "Signal",
    text: "A pure function diffs current vs. prior snapshot and ranks what changed by significance: magnitude times how unusual the move is against that protocol's own volatility.",
  },
  {
    name: "Agent",
    text: "DeepSeek writes the high-frequency dashboard briefs; Claude runs the tool-using conversational agent. Each is the other's fallback.",
  },
  {
    name: "Surface",
    text: "Four distribution surfaces (dashboard, chat, CLI, LLM skill) all consume this same pipeline. None is a reduced implementation of another.",
  },
];

function Eyebrow({ children }) {
  return <span className="font-mono text-[11px] uppercase tracking-wider text-paper-faint">{children}</span>;
}

function Section({ num, eyebrow, title, children }) {
  return (
    <div className="border-t border-hairline py-12 first:border-t-0 first:pt-0">
      <div className="flex items-baseline gap-3">
        <span className="font-mono text-[13px] text-signal">{num}</span>
        <Eyebrow>{eyebrow}</Eyebrow>
      </div>
      <h2 className="mt-2 text-2xl font-semibold tracking-tight text-paper">{title}</h2>
      <div className="mt-4 max-w-2xl space-y-4 text-[15px] leading-relaxed text-paper-dim">{children}</div>
    </div>
  );
}

export default function Docs({ onBack }) {
  return (
    <section className="mx-auto max-w-4xl px-5 py-8 lg:px-8 lg:py-12">
      <button
        onClick={onBack}
        className="mb-6 flex items-center gap-2 self-start font-mono text-[13px] text-paper-faint transition-colors hover:text-paper lg:mb-8"
      >
        ← Back to dashboard
      </button>

      <Eyebrow>Whitepaper · v1.0</Eyebrow>
      <h1 className="mt-2 text-[28px] font-semibold leading-tight tracking-tight text-paper lg:text-4xl">
        Conduit: the onchain research agent for Mantle.
      </h1>
      <p className="mt-4 max-w-2xl text-[15px] leading-relaxed text-paper-dim lg:text-[16px]">
        Conduit converts raw onchain data into interpreted signal. It combines a live data pipeline, a
        significance-ranking layer, and a dual-provider LLM agent to answer, in under a minute, what today takes a
        researcher hours of manual cross-referencing: what is actually happening on Mantle right now, and why does
        it matter. Every figure shown is fetched at request time; every interpretation is generated by a live model
        call. Nothing on the default path is pre-written or fabricated.
      </p>

      <Section num="01" eyebrow="Problem" title="Onchain data is public. Understanding it isn't.">
        <p>
          Reading the actual state of a chain like Mantle today means manually stitching together explorers,
          protocol dashboards, and ad hoc queries, then forming a judgment by hand. The friction isn't access. It's
          synthesis. A researcher can see that a protocol's TVL moved, but not whether that move is routine noise or
          the most significant thing that happened on the chain that week.
        </p>
        <p>
          Conduit closes that gap by doing what a human researcher does, at machine speed: it watches the ecosystem,
          detects what changed, ranks it by significance, and explains it in plain language, with the option to ask
          it anything further and have it go look.
        </p>
      </Section>

      <Section num="02" eyebrow="Principles" title="Live data. Live inference. Disclosed provenance.">
        <p>
          <strong className="text-paper">Live data only.</strong> Every number shown is fetched from Mantle's public
          RPC or DefiLlama's public API at request time; nothing hardcoded on the default path.
        </p>
        <p>
          <strong className="text-paper">Live inference only.</strong> Every brief and every chat reply is generated
          by a model call that receives the current data as input, not a stored string.
        </p>
        <p>
          <strong className="text-paper">Disclosed degradation.</strong> Every claim traces to a source link. If a
          live source is unreachable and the system falls back to a cached or bundled snapshot, that's shown as a
          visible banner, not silently absorbed.
        </p>
      </Section>

      <Section num="03" eyebrow="Architecture" title="Four layers, all real.">
        <div className="space-y-4">
          {LAYERS.map((layer) => (
            <div key={layer.name}>
              <span className="font-mono text-[13px] text-paper">{layer.name}</span>
              <p className="text-[14px] leading-relaxed text-paper-dim">{layer.text}</p>
            </div>
          ))}
        </div>
      </Section>

      <Section num="04" eyebrow="Methodology" title="Significance, not just size.">
        <p>
          Raw percentage change is a poor significance measure on its own: a large, stable protocol drifting 1% is
          noise, while a small, usually-quiet protocol moving three times its typical weekly swing is a real signal.
          Each tracked protocol is scored as:
        </p>
        <pre className="overflow-x-auto rounded-xl border border-hairline bg-panel p-4 font-mono text-[13px] leading-relaxed text-paper-dim">
{`significance = |7-day % change| × unusualness
unusualness  = |7-day % change| ÷ (that protocol's own trailing daily
               volatility × √7), capped at 8×`}
        </pre>
        <p>
          Volatility is computed per protocol from its own trailing daily return series, so a naturally volatile DEX
          and a naturally stable lending market are each judged against their own baseline. Separately, tracked
          protocols are classified as active capital (Dexs, Lending) versus idle capital (RWA) using DefiLlama's own
          category taxonomy: a disclosed, reproducible methodology, not an invented score.
        </p>
      </Section>

      <Section num="05" eyebrow="Research agent" title="Real tool calls, not a stuffed context.">
        <p>
          Dashboard briefs are short, plain-English writeups generated at request time from the current ranked data.
          The chat surface goes further: it runs a genuine agentic tool-use loop, deciding on each turn whether to
          search the web or call one of Conduit's own data tools.
        </p>
        <div className="space-y-3">
          {TOOLS.map((tool) => (
            <div key={tool.name}>
              <span className="font-mono text-[13px] text-paper">{tool.name}</span>
              <p className="text-[14px] leading-relaxed text-paper-dim">{tool.text}</p>
            </div>
          ))}
        </div>
        <p>
          Each tool call streams to the client as a visible status line before its result returns, every URL touched
          is collected into a clickable source list, and each reply is tagged with a topic label determined
          deterministically from the real protocol registry, not asked of the model. If Claude is unavailable
          mid-turn, the turn retries on DeepSeek with a quiet note attached; if neither provider is reachable, the
          agent says so directly rather than guessing.
        </p>
      </Section>

      <Section num="06" eyebrow="Access control" title="Connect once, 10 messages a day.">
        <p>
          The conversational agent requires a connected wallet before it will respond: any injected, EIP-1193
          provider (MetaMask, Rabby, OKX, and similar). No WalletConnect step, no signature: connecting supplies only
          an address, used to meter usage, not to authenticate ownership.
        </p>
        <p>
          Each wallet is limited to ten messages per rolling UTC day, enforced server-side and shown live in the
          chat header as it counts down. This is a rate limit on a free feature, not a security boundary.
        </p>
      </Section>

      <Section num="07" eyebrow="Surfaces" title="Not confined to a browser tab.">
        <p>
          Three surfaces share the identical pipeline and agent logic. None is a reduced implementation of another.
        </p>
        <div>
          <span className="font-mono text-[13px] text-paper">Terminal</span>
          <p className="mt-1 text-[14px] leading-relaxed text-paper-dim">
            The same agent and tool-use logic, running as a terminal REPL against a fresh live snapshot on launch.
          </p>
          <div className="mt-3 max-w-md">
            <CopyCommand command="npx conduit-mantle" />
          </div>
        </div>
        <div>
          <span className="font-mono text-[13px] text-paper">LLM skill</span>
          <p className="mt-1 text-[14px] leading-relaxed text-paper-dim">
            A dependency-free Node script (no npm install, no API key) that ports the read-only half of the pipeline
            into a form any LLM or agent runtime can call directly, mid-conversation.
          </p>
          <a
            href="/downloads/conduit-mantle-skill.zip"
            download
            className="mt-3 inline-flex items-center gap-2 rounded-full border border-hairline-strong px-5 py-2.5 text-[13px] font-medium text-paper transition-colors hover:border-paper"
          >
            Download conduit-mantle-skill.zip
          </a>
        </div>
      </Section>

      <Section num="08" eyebrow="Scope" title="What's shipped, what isn't.">
        <p>
          Conduit today tracks eleven near-native Mantle protocols in depth (Merchant Moe, Agni Finance, Fluxion
          Network, INIT Capital, Lendle, Mantle Index Four Fund, FusionX V3, Solv RWA, Circuit Protocol, Aurelius,
          and Puff Penthouse) with full historical TVL and signal ranking, plus on-demand search and detail lookup
          across every other protocol DefiLlama tracks on Mantle.
        </p>
        <p>
          Not yet built, and not claimed as built: per-wallet behavioral analytics, a narrative-versus-reality
          sentiment overlay, treasury-activity correlation tracking, and drilldowns into specific named tokenized
          real-world assets beyond DefiLlama's own categorization. These generalize naturally from the existing
          architecture but are future work, not present functionality.
        </p>
      </Section>

      <Section num="09" eyebrow="Conclusion" title="Read the chain, not just the charts.">
        <p>
          A live data pipeline feeds a disclosed significance methodology, which feeds a tool-using agent that can
          go verify anything it's unsure of, across surfaces that all share the same underlying truth. Every number
          in front of you was fetched, not remembered. Every sentence around it was written just now, not stored.
        </p>
      </Section>
    </section>
  );
}
